apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n3upml3v2-nodejs
  janus-idp.io/tekton: n3upml3v2-nodejs
  backstage.io/kubernetes-id: n3upml3v2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n3upml3v2-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
